Ddl plouie.dom 39750.no queue declare on every publish
dominodatalab/seldon-core pull request #6
Opened 2022-09-30 20:47 UTC by ddl-plouie

**What this PR does / why we need it**:
Removed QueueDeclare() on every message.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2022-10-03 15:53 UTC, dmcwhorter-ddl commented on executor/api/grpc/kfserving/inference/grpc_service.pb.go
> -//@@
please revert changes to this file

2022-10-03 15:53 UTC, dmcwhorter-ddl commented on executor/api/grpc/kfserving/inference/model_config.pb.go
> -//@@
please revert changes to this file

2022-10-03 15:54 UTC, dmcwhorter-ddl commented on executor/api/rabbitmq/publisher_test.go
> +		//mockChan.On("QueueDeclare", queueName, true, false, false, false,
please remove commented code

2022-10-03 15:54 UTC, dmcwhorter-ddl commented on executor/api/rabbitmq/publisher_test.go
> +			//channel.On("QueueDeclare", queueName, true, false, false, false,
please remove commented code

2022-10-03 15:54 UTC, dmcwhorter-ddl commented on executor/api/rabbitmq/publisher_test.go
> +			//	queueArgs).Return(amqp.Queue{Name: queueName},
same

2022-10-03 15:55 UTC, dmcwhorter-ddl commented on executor/api/rabbitmq/server_test.go
> -	invalidErrorJsonResponse := fmt.Sprintf(
this should still be there, this is unrelated to QueueDeclare

2022-10-03 15:55 UTC, dmcwhorter-ddl commented on executor/api/rabbitmq/server_test.go
> -	t.Run("serve", func(t *testing.T) {
This is one of the main tests for the server, it should be updated to work with the changes and not removed

2022-10-03 15:56 UTC, dmcwhorter-ddl commented on executor/api/rabbitmq/server_test.go
> -	t.Run("serveError", func(t *testing.T) {
this should be updated and not removed

2022-10-03 15:56 UTC, dmcwhorter-ddl requested changes
Please fix test cases

2022-10-03 15:56 UTC, dmcwhorter-ddl commented
@ddl-plouie the integration test is failing (circleCI workflow above)

2022-10-03 20:45 UTC, ddl-plouie commented on executor/api/grpc/kfserving/inference/grpc_service.pb.go
> -//@@
Discussed

2022-10-03 20:45 UTC, ddl-plouie commented on executor/api/rabbitmq/publisher_test.go
> +		//mockChan.On("QueueDeclare", queueName, true, false, false, false,
Discussed

2022-10-03 20:46 UTC, ddl-plouie commented on executor/api/rabbitmq/publisher_test.go
> +			//	queueArgs).Return(amqp.Queue{Name: queueName},
Done

2022-10-03 20:46 UTC, ddl-plouie commented on executor/api/rabbitmq/server_test.go
> -	t.Run("serve", func(t *testing.T) {
Done

2022-10-03 20:46 UTC, ddl-plouie commented on executor/api/rabbitmq/server_test.go
> -	t.Run("serveError", func(t *testing.T) {
Done

2022-10-04 15:16 UTC, dmcwhorter-ddl approved these changes

2022-10-04 16:40 UTC, merged